name: Docker Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  terraform:
    uses: ./.github/workflows/terraform.yml
    secrets:
      AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_db_password: ${{ secrets.TF_VAR_DB_PASSWORD }}

  build:

    runs-on: ubuntu-latest
    needs: terraform
    env:
      REPOSITORY_URL: ${{ needs.terraform.outputs.repository_url }}
    steps:
    - name: "Echo"
      run: echo "$REPOSITORY_URL"
    # - uses: actions/checkout@v3
    # - name: Build the Docker image
    #   run: docker build django-app --file docker/Dockerfile --tag django-app:$(date +%s)

  deploy:
    runs-on: ubuntu-latest
    needs: terraform
    env:
      REPOSITORY_URL: ${{ needs.terraform.outputs.repository_url }}
    steps:
      - run: echo "$REPOSITORY_URL"
